(define (sqrt-iter last-guess guess x) 
	(if (good-enough? last-guess guess x) 
		guess (sqrt-iter guess (improve guess x) x)
		)
	)

(define (square x) 
	(* x x)
	)
(define (improve guess x) 
	(average guess (/ x guess))
	)
(define (average x y) (/ (+ x y) 2))

(define (good-enough? last-guess guess x) 
	(< (/ (abs (- last-guess guess))
		x)
	 0.001))

(define (sqrt x) (sqrt-iter 0 1.0 x))
(display (sqrt 0.000000000000000000000009))